service: event-bridge

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource:
        - arn:aws:events:*

functions:
 notify:
   handler: handler.handler
   events:
     - eventBridge:
        eventBus: marketing 
        pattern:
           source:
             - acme.newsletter.campaign

 email:
  handler: eventEmail.handler
  events:
    - http:
          path: subiscribe
          method: post
    
   
